### PR TITLE
add credential management

### PR DESCRIPTION
**Pull request by xiaoranzhou**
credential management using prompt and keyring

### CODE REVIEW

**Comment by bedroesb** [comment]
@xiaoranzhou thanks a lot for this addition. We might want to first decide how we handle multiple credentials for multiple repositories.

How would you implement this with your method based on the username (if I understand things correctly :) )? I see a use in the env variables but a prompt looks counter intuitive for the implementations we are looking into I think (Galaxy, ARC, different webbapp or even a CLI because than putting it in a pipeline become less easy) .

**Comment by xiaoranzhou** [comment]
> @xiaoranzhou thanks a lot for this addition. We might want to first decide how we handle multiple credentials for multiple repositories.
> 
> How would you implement this with your method based on the username (if I understand things correctly :) )? I see a use in the env variables but a prompt looks counter intuitive for the implementations we are looking into I think (Galaxy, ARC, different webbapp or even a CLI because than putting it in a pipeline become less easy) .

Yes, this is a collection of options we could have. Including environment variable, prompt and system secret management. We should provide many ways to store credential. We need to decide the priority of the three methods and the pipeline to check or let user decide which one to use.

**Review by kdp-cloud — APPROVED** [review]
Nice work!
According to the documentation, it should also work with a `~/.credentials.json` file.
I think it would be nice if you could add an example file like this for testing purpose.
But it can be done later as well. Should not be a blocker...

**Comment by bedroesb** [comment]
I will merge this pull request so it can be used as starting point later on. We should keep in mind it is not yet "integrated" after this merge. Thanks @xiaoranzhou !

**Pull request merged**
