### PR TITLE
Mars receipt exception

### LINKED ISSUE #67: Repository API receipt error catching
Currently, when for example no data is submitted before metadata submission, ENA will return errors in the "messages" filed. The script can currently not find accessions in those messages:
https://github.com/elixir-europe/MARS/blob/main/repository-services/isajson-ena/src/main/java/com/elixir/biohackaton/ISAToSRA/sra/service/MarsReceiptService.java#L76

this needs to be captured

### PR DESCRIPTION
**Pull request by Pedram-A-Keyvani**
Showing errors in MARS receipt in the happening of:
- `MarsReceiptException` that are custom errors from the API
- `Exception` for catching all the other errors

**CAUTION**: The receipt errors might contain technical information

### CODE REVIEW

**Comment by Pedram-A-Keyvani** [comment]
#67 closed

**Review by apriltuesday — APPROVED** [review]
Looks good! As we discussed, I think this will help us start handling errors in the CLI, so we can continue to iterate on this.

**Comment by bedroesb** [comment]
Thanks a lot @Pedram-A-Keyvani!

**Comment by bedroesb** [comment]
I just tested the code, and triggered an error by doing a submission twice using the same data:
```
mars-cli --development submit          --credential-service-name biosamples          --credentials-file /home/bedro/Documents/MARS/mars-cli/tests/test_credentials_example.json          --file-transfer ftp          --data-files /home/bedro/Documents/MARS/test-data/ENA_TEST2.R2.fastq.gz   --submit-to-metabolights False      --output final-isa          /home/bedro/Documents/MARS/test-data/biosamples-input-isa.json
/home/bedro/.config/python_keyring
keyring.backends.SecretService.Keyring (priority: 5)
############# Welcome to the MARS CLI. #############
Running in Development environment
Starting submission of the ISA JSON to the target repositories: biosamples, ena.
ISA JSON with investigation 'Bob's investigation' is valid.
Submission to TargetRepository.BIOSAMPLES was successful. Result:
{'targetRepository': 'biosamples', 'errors': [], 'info': [], 'accessions': [{'value': 'SAMEA131504279', 'path': [{'key': 'investigation'}, {'key': 'studies', 'where': {'key': 'title', 'value': 'Arabidopsis thaliana'}}, {'key': 'materials'}, {'key': 'samples', 'where': {'key': 'name', 'value': 'leaf 1'}}]}, {'value': 'SAMEA131504278', 'path': [{'key': 'investigation'}, {'key': 'studies', 'where': {'key': 'title', 'value': 'Arabidopsis thaliana'}}, {'key': 'materials'}, {'key': 'sources', 'where': {'key': 'name', 'value': 'plant 1'}}]}]}
#sample/331: comments=[] id='#ontology_annotation/accession_#sample/331' annotationValue='SAMEA131504279' termAccession=None termSource=None.
#source/330: comments=[] id='#ontology_annotation/accession_#source/330' annotationValue='SAMEA131504278' termAccession=None termSource=None.
ENA_TEST2.R2.fastq.gz already exists and has the same size on the FTP, skipping
Start submitting to TargetRepository.ENA.
Submission to TargetRepository.ENA was successful. Result:
{'targetRepository': 'ena', 'errors': [{'type': 'INVALID_METADATA', 'message': 'ENA receipt: Accession number of Arabidopsis thaliana-0.7403975790744531 is NULL'}, {'type': 'INVALID_METADATA', 'message': 'ENA receipt: Accession number of #other_material/332-0.7403975790744531 is NULL'}, {'type': 'INVALID_METADATA', 'message': 'ENA receipt: Accession number of #other_material/333-0.7403975790744531 is NULL'}, {'type': 'INVALID_METADATA', 'message': 'ENA receipt: Accession number of #assay/18_20_21-0.7403975790744531 is NULL'}, {'type': 'INVALID_METADATA', 'message': 'File ENA_TEST2.R2.fastq.gz has already been submitted in ERR14097866 and is waiting to be processed'}], 'info': [{'message': 'This submission is a TEST submission and will be discarded within 24 hours'}], 'accessions': []}
Update ISA-JSON based on receipt from TargetRepository.ENA.
```

Just as a note, the current MARS CLI still dumps a updated ISA JSON with the BioSamples accessions, which is I think a desired behavior.

**Review by bedroesb — APPROVED** [review]

**Pull request merged**
